export const cicdApi = {
  dmCicdFlowList: '/clouddm/console/api/v1/cicd/flow/list',
  dmCicdDevopsUsers: '/clouddm/console/api/v1/cicd/flow/users',
  dmCicdCreate: '/clouddm/console/api/v1/cicd/flow/create',
  dmCicdDevopsScmList: '/clouddm/console/api/v1/cicd/flow/gitOpsScmList',
  dmCicdDevopsRepos: '/clouddm/console/api/v1/cicd/flow/gitOpsRepos',
  dmCicdDevopsDsInsLevels: '/clouddm/console/api/v1/cicd/flow/dsInsLevels',
  dmCicdDevopsDsDbLevels: '/clouddm/console/api/v1/cicd/flow/dsDbLevels',

  dmCicdFlowDetail: '/clouddm/console/api/v1/cicd/flow/detail',
  dmCicdFlowUpdate: '/clouddm/console/api/v1/cicd/flow/update',
  dmCicdFlowDevopsList: '/clouddm/console/api/v1/cicd/flow/gitOpsList',
  dmCicdFlowFetchImConfig: '/clouddm/console/api/v1/cicd/flow/fetchImConfig',
  dmCicdFlowPushImConfig: '/clouddm/console/api/v1/cicd/flow/pushImConfig',
  dmCicdFlowPushFlowConfig: '/clouddm/console/api/v1/cicd/flow/pushFlowConfig',
  dmCicdFlowDevopsCreate: '/clouddm/console/api/v1/cicd/flow/gitOpsCreate',
  dmCicdFlowDevopsDelete: '/clouddm/console/api/v1/cicd/flow/gitOpsDelete',
  dmCicdFlowDevopsSwitch: '/clouddm/console/api/v1/cicd/flow/switch',
  dmCicdFlowArchive: '/clouddm/console/api/v1/cicd/flow/archive',
  dmCicdFlowRecover: '/clouddm/console/api/v1/cicd/flow/recover',
  dmCicdFlowDelete: '/clouddm/console/api/v1/cicd/flow/delete',
  dmCicdFlowTriggerChange: '/clouddm/console/api/v1/cicd/flow/triggerChange',
  dmCicdFlowTriggerSnapshot: '/clouddm/console/api/v1/cicd/flow/triggerSnapshot',
  dmCicdFlowTriggerConfig: '/clouddm/console/api/v1/cicd/flow/triggerConfig',
  dmCicdFlowCallBackConfig: '/clouddm/console/api/v1/cicd/flow/callbackConfig',

  dmCicdChangeList: '/clouddm/console/api/v1/cicd/change/changeList',
  dmCicdChangeDetail: '/clouddm/console/api/v1/cicd/change/changeDetail',
  dmCicdChangeBody: '/clouddm/console/api/v1/cicd/change/changeBody',
  dmCicdChangeChecks: '/clouddm/console/api/v1/cicd/change/changeChecks',
  dmCicdChangeClose: '/clouddm/console/api/v1/cicd/change/changeClose',
  dmCicdChangeApproval: '/clouddm/console/api/v1/cicd/change/changeApproval',
  dmCicdChangeConfirmExec: '/clouddm/console/api/v1/cicd/change/confirmExec',
  dmCicdChangeSkipChecks: '/clouddm/console/api/v1/cicd/change/skipChecks',
  dmCicdChangeRetry: '/clouddm/console/api/v1/cicd/change/changeRetry',
  dmCicdChangeExecTaskList: '/clouddm/console/api/v1/cicd/change/changeExecTaskList',
  dmCicdChangeExecute: '/clouddm/console/api/v1/cicd/change/changeExecute'
};
