export const financeApi = {
  // userInvoiceApplyCount: '/api/entry/finance/userInvoiceApplyCount',
  // pageListUserInvoiceApply: '/api/entry/finance/pageListUserInvoiceApply',
  // cancelInvoiceApply: '/api/entry/finance/cancelInvoiceApply',
  // modifyInvoiceApply: '/api/entry/finance/modifyInvoiceApply',
  // userUnInvoicedOrderCount: '/api/entry/finance/userUnInvoicedOrderCount',
  // pageListUserUnInvoicedOrder: '/api/entry/finance/pageListUserUnInvoicedOrder',
  // userUnInvoicedMonthlyBillCount: '/api/entry/finance/userUnInvoicedMonthlyBillCount',
  // pageListUserUnInvoicedMonthlyBill: '/api/entry/finance/pageListUserUnInvoicedMonthlyBill',
  // calculateInvoiceAmount: '/api/entry/finance/calculateInvoiceAmount',
  // applyInvoice: '/api/entry/finance/applyInvoice',
  // queryUserBalance: '/api/entry/finance/queryUserBalance',
  // changeBalanceNeedAlert: '/api/entry/finance/changeBalanceNeedAlert',
  // changeAlertBalance: '/api/entry/finance/changeAlertBalance',
  // createPrepay: '/api/entry/finance/createPrepay',
  // payUrlGenForPrepay: '/api/entry/finance/payUrlGenForPrepay',
  // userPrepayCount: '/api/entry/finance/userPrepayCount',
  // pageListUserPrepays: '/api/entry/finance/pageListUserPrepays',
  // cancelPrepay: '/api/entry/finance/cancelPrepay',

  // rdp
  rdpFinanceUserInvoiceApplyCount: '/api/entry/finance/userInvoiceApplyCount',
  rdpFinancePageListUserInvoiceApply: '/api/entry/finance/pageListUserInvoiceApply',
  rdpFinanceCancelInvoiceApply: '/api/entry/finance/cancelInvoiceApply',
  rdpFinanceModifyInvoiceApply: '/api/entry/finance/modifyInvoiceApply',
  rdpFinanceUserUnInvoicedOrderCount: '/api/entry/finance/userUnInvoicedOrderCount',
  rdpFinancePageListUserUnInvoicedOrder: '/api/entry/finance/pageListUserUnInvoicedOrder',
  rdpFinanceUserUnInvoicedMonthlyBillCount: '/api/entry/finance/userUnInvoicedMonthlyBillCount',
  rdpFinancePageListUserUnInvoicedMonthlyBill: '/api/entry/finance/pageListUserUnInvoicedMonthlyBill',
  rdpFinanceCalculateInvoiceAmount: '/api/entry/finance/calculateInvoiceAmount',
  rdpFinanceApplyInvoice: '/api/entry/finance/applyInvoice',
  rdpFinanceQueryUserBalance: '/api/entry/finance/queryUserBalance',
  rdpFinanceChangeBalanceNeedAlert: '/api/entry/finance/changeBalanceNeedAlert',
  rdpFinanceChangeAlertBalance: '/api/entry/finance/changeAlertBalance',
  rdpFinanceCreatePrepay: '/api/entry/finance/createPrepay',
  rdpFinancePayUrlGenForPrepay: '/api/entry/finance/payUrlGenForPrepay',
  rdpFinanceUserPrepayCount: '/api/entry/finance/userPrepayCount',
  rdpFinancePageListUserPrepays: '/api/entry/finance/pageListUserPrepays',
  rdpFinanceCancelPrepay: '/api/entry/finance/cancelPrepay'
};
