export const securityApi = {
  dmSecurityRulesRuleList: '/api/entry/security/rules/ruleList',
  dmSecurityRulesRuleDetail: '/api/entry/security/rules/ruleDetail',
  dmSecurityRulesRuleSave: '/api/entry/security/rules/ruleSave',
  dmSecurityRulesRuleDelete: '/api/entry/security/rules/ruleDelete',
  dmSecurityRulesRuleExtract: '/api/entry/security/rules/ruleExtract',
  dmSecurityRulesRuleSupportDs: '/api/entry/security/rules/ruleSupportDs',
  dmSecurityRulesRuleSettingDef: '/api/entry/security/support/ruleSettingDef',
  dmSecurityRulesSpecRuleDetail: '/api/entry/security/rules/specRuleDetail',
  dmSecurityRulesSpecFetchRange: '/api/entry/security/range/specFetchRange',
  dmSecurityRulesSpecSaveRange: '/api/entry/security/range/specSaveRange',
  dmSecurityRulesSpecDeleteRange: '/api/entry/security/range/specDeleteRange',
  dmSecurityRulesSpecList: '/api/entry/security/rules/specList',
  dmSecurityRulesSpecDetail: '/api/entry/security/rules/specDetail',
  dmSecurityRulesSpecUpdateInfo: '/api/entry/security/rules/specUpdateInfo',
  dmSecurityRulesSpecConfig: '/api/entry/security/rules/specConfig',
  dmSecurityRulesSpecDelete: '/api/entry/security/rules/specDelete',
  dmSecurityRulesSpecCreate: '/api/entry/security/rules/specCreate',
  dmSecurityRulesSpecSaveRule: '/api/entry/security/rules/specSaveRule',
  dmSecurityRulesSpecSaveRules: '/api/entry/security/rules/specSaveRules',

  dmSecurityRangeListEnv: '/api/entry/security/range/listEnv',
  dmSecurityRangeListIns: '/api/entry/security/range/listIns',
  dmSecurityRangeListLevels: '/api/entry/security/range/listLevels',
  dmSecurityRangeListLeaf: '/api/entry/security/range/listLeaf',
  dmSecurityRangeListColumn: '/api/entry/security/range/listColumn'
};
