-- Step 6 parser fixture. Creates objects: run only in a disposable schema.
CREATE COLUMN TABLE "HANA_SPLIT_T" ("ID" INTEGER PRIMARY KEY, "V;" NVARCHAR(100));
INSERT INTO "HANA_SPLIT_T" VALUES (1, 'a;''b');
UPDATE "HANA_SPLIT_T" SET "V;" = 'updated' WHERE "ID" = 1;
DELETE FROM "HANA_SPLIT_T" WHERE "ID" = 99;
/* A comment with ; BEGIN END IF does not change statement boundaries. */
WITH "CTE;" AS (SELECT 'cte;' AS "V" FROM DUMMY)
SELECT "V" FROM "CTE;";
MERGE INTO "HANA_SPLIT_T" T USING (SELECT 2 AS ID FROM DUMMY) S ON T."ID" = S.ID
WHEN MATCHED THEN UPDATE SET T."V;" = 'matched;'
WHEN NOT MATCHED THEN INSERT ("ID", "V;") VALUES (S.ID, 'new;');
CREATE OR REPLACE PROCEDURE "HANA_SPLIT_P" () LANGUAGE SQLSCRIPT AS
BEGIN
    DECLARE N INTEGER = 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        SELECT ::SQL_ERROR_CODE AS "ERROR_CODE" FROM DUMMY;
    END;
    FOR I IN 1..2 DO
        IF :I = 1 THEN
            N = :N + 1;
        ELSEIF :I = 2 THEN
            N = :N + 2;
        ELSE
            N = 0;
        END IF;
    END FOR;
    WHILE :N < 4 DO
        N = :N + 1;
    END WHILE;
    LOOP
        BREAK;
    END LOOP;
    BEGIN
        SELECT CASE WHEN :N = 4 THEN 'four;' ELSE 'other;' END AS "VALUE" FROM DUMMY;
    END;
END;
CALL "HANA_SPLIT_P"();
CREATE OR REPLACE FUNCTION "HANA_SPLIT_F" () RETURNS RESULT INTEGER LANGUAGE SQLSCRIPT AS
BEGIN
    RESULT = 1;
END;
DO BEGIN
    DECLARE MESSAGE NVARCHAR(100) = 'do;''block';
    SELECT :MESSAGE AS "TEXT;", CASE WHEN 1 = 1 THEN CASE WHEN 2 = 2 THEN 'yes;' ELSE 'no' END ELSE 'no' END AS "NESTED" FROM DUMMY;
END;
SELECT "HANA_SPLIT_F"() FROM DUMMY;
DROP FUNCTION "HANA_SPLIT_F";
DROP PROCEDURE "HANA_SPLIT_P";
DROP TABLE "HANA_SPLIT_T";
