-- HANA 2.0 Platform: read-only examples. Set the UI row limit to 1.
SELECT 1 AS V FROM DUMMY UNION ALL SELECT 2 AS V FROM DUMMY ORDER BY V;
SELECT TOP 2 * FROM (SELECT 1 AS V FROM DUMMY UNION ALL SELECT 2 AS V FROM DUMMY) T ORDER BY V;
SELECT * FROM (SELECT 1 AS V FROM DUMMY UNION ALL SELECT 2 AS V FROM DUMMY) T ORDER BY V LIMIT 2 OFFSET 0;
SELECT 1 AS V FROM DUMMY LIMIT 0;
WITH C AS (SELECT 1 AS V FROM DUMMY UNION ALL SELECT 2 AS V FROM DUMMY) SELECT * FROM C ORDER BY V;
SELECT 'a;b 😀' AS "Mixed Case" FROM DUMMY; -- preserve this comment
-- Formatting / structural diagnostics only; execution still depends on step 8.
DO BEGIN SELECT 'a;b' AS V FROM DUMMY; SELECT 2 AS V FROM DUMMY; END;
