-- Static analysis fixtures only. Do not execute this file as a batch.
-- Names APP/OTHER/SECRET are placeholders, not existing grants or objects.
-- For live checks use disposable schemas as described in hana_query_authorization.md.
SELECT T.ID FROM APP.T T JOIN OTHER.S S ON T.ID = S.ID
WHERE EXISTS (SELECT 1 FROM SECRET.U U WHERE U.ID = T.ID);
WITH C AS (SELECT * FROM OTHER.S) SELECT * FROM C;
UPDATE A SET V = 1 FROM OTHER.S A WHERE A.ID = 1;
INSERT INTO APP.T (ID, V) SELECT ID, V FROM OTHER.S;
DELETE FROM APP.T WHERE ID = 1;
MERGE INTO APP.T T USING OTHER.S S ON T.ID = S.ID
WHEN MATCHED THEN UPDATE SET T.V = S.V
WHEN NOT MATCHED THEN INSERT (ID, V) VALUES (S.ID, S.V);
UPSERT INTO APP.T (ID, V) VALUES (1, 2) WITH PRIMARY KEY;
SELECT * FROM "A.B"."T.X";
SELECT 'DELETE FROM SECRET.U;' FROM APP.T; -- FROM SECRET.U is not a relation
SELECT OTHER.SEQ.NEXTVAL, OTHER.SEQ.CURRVAL FROM APP.T;
CALL OTHER.P();
SELECT OTHER.F(ID) FROM APP.T;
DO BEGIN
    X = SELECT * FROM OTHER.S;
    IF 1 = 1 THEN
        X = SELECT * FROM SECRET.U;
    END IF;
    SELECT * FROM :X;
    UPDATE APP.T SET V = 1;
END;
CREATE TABLE APP.T_NEW (
    ID INTEGER,
    PID INTEGER REFERENCES OTHER.PARENT(ID),
    V INTEGER UNIQUE,
    PRIMARY KEY (ID)
);
ALTER TABLE APP.T_NEW DROP CONSTRAINT FK_TEST;
CREATE PROCEDURE APP.P() LANGUAGE SQLSCRIPT DEFAULT SCHEMA OTHER AS
BEGIN
    SELECT * FROM S;
END;

-- Analyze these negative cases separately; each must fail, with no execute/audit success:
-- DO BEGIN SELECT * FROM APP.T; EXECUTE IMMEDIATE 'DELETE FROM APP.T'; END;
-- SELECT * FROM REMOTE.S.T;
-- UPDATE APP.T SET V = 1 GARBAGE;
-- SELECT * FROM :UNDECLARED;
-- DROP INDEX APP.IX;
-- SET SCHEMA OTHER; -- when editor context is APP
