-- HANA 第 9 步血缘/脱敏样本。替换 H9_A / H9_B 为本次隔离 schema 后逐条运行。
-- 建表/造数及权限配置见 tests/frontend/security/hana_lineage_masking.md。
-- SELECT 表达式使用显式别名，确保血缘输出名与 JDBC 列标签一致。
SELECT SECRET AS RENAMED FROM H9_A.T;
SELECT UPPER(SECRET) AS TRANSFORMED FROM H9_A.T;
SELECT A.SECRET || B.SECRET AS COMBINED
FROM H9_A.T A JOIN H9_B.S B ON A.ID = B.ID;
SELECT A.* FROM H9_A.T A;
WITH C(X) AS (SELECT SECRET FROM H9_A.T) SELECT X AS RENAMED FROM C;
SELECT X FROM (SELECT SECRET AS X FROM H9_A.T) D;
SELECT (SELECT MAX(B.SECRET) FROM H9_B.S B WHERE B.ID = A.ID) AS SCALAR_VALUE
FROM H9_A.T A;
SELECT SECRET AS COMBINED FROM H9_A.T
UNION ALL SELECT SECRET FROM H9_B.S;
SELECT "foo" AS LOWER_NAME, FOO AS UPPER_NAME FROM H9_A.T;
SELECT V.* FROM H9_A.V;
SELECT 'literal' AS CONSTANT_VALUE, SECRET FROM H9_A.T;

-- 以下负例必须停止 SELECT 执行，不得把未知来源当成常量或无须脱敏。
SELECT MISSING FROM H9_A.T;
SELECT SECRET || PUBLIC_VALUE FROM H9_A.T;
SELECT SESSION_CONTEXT('H9_VALUE') AS UNKNOWN_VALUE FROM H9_A.T;
SELECT * FROM :UNKNOWN_TABLE;
SELECT H9_A.UNKNOWN_FUNCTION(SECRET) AS UNKNOWN_VALUE FROM H9_A.T;
