##############################################################
##                                                   Server ##
##############################################################
server.port=8222
clouddm.rsocket.dns=127.0.0.1
clouddm.rsocket.console.port=8008
jwt.secret=jwt67843ad4s118123ycgve45uk12ghd3vli4u510fd9z35hec2hegre876n1g3sa8s2o
##############################################################
##                                               DataSource ##
##############################################################
spring.datasource.jdbcurl=jdbc:mysql://127.0.0.1:3306/cdmgr
spring.datasource.username=
spring.datasource.password=
##############################################################
##                                                DM Config ##
##############################################################
clougence.rdp.console.oppassword=false
clouddm.console.max-tx-session-user=20
clougence.rdp.black.ds.self=Dameng,Hana,Redshift,\
  Kafka,RocketMQ,RabbitMQ,AutoMQ,DeltaLake,Hive,ElasticSearch,Kudu,\
  Tunnel,Hudi,Lindorm,DocumentDB,Iceberg,Pulsar,GreptimeDB,TDengine,SshFile,LocalAI,RagApi,Ollama,DuckDB,Paimon,GoogleDrive,Yuque
clougence.rdp.black.ds.aliyun=ClickHouse,ElasticSearch,Greenplum,Kafka,RabbitMQ,RocketMQ,SQLServer,DashScope,DataLakeFormation,OssFile
clougence.rdp.black.ds.aws=AuroraMySQL,AuroraPostgreSQL,DocumentDB,MariaDB,Oracle,Redshift,SQLServer,S3File,Bedrock,ElastiCache,AmazonMSK,DynamoDB
clougence.rdp.black.ds.azure=
clougence.rdp.black.ds.huawei=GaussDBForMySQL,
clougence.rdp.black.ds.independent=OpenAI,HuggingFace,Cohere,DeepSeek
clougence.rdp.black.deploy=HUAWEI_CLOUD_HOSTED,INDEPENDENT_CLOUD_PLATFORM,TENCENT_CLOUD_HOSTED
console.config.cross.origins=*
