package com.clougence.clouddm.team.provider.wechat.utils.aes;

/** Regarding org.json JSONObject,
 * To compile the packaging rack package JSON
 * Official source code download link: https://github.com/stleary/JSON-java , Jar package download address: https://mvnrepository.com/artifact/org.json/json */

import org.json.JSONObject;

import com.clougence.clouddm.team.provider.wechat.constants.WechatI18nKey2;
import com.clougence.clouddm.sdk.model.exception.ThirdPartyApiException;

/**
 * JsonParse class
 * Provide an interface for extracting ciphertext from message formats and generating reply message formats
 */
class JsonParse {

    /**
     * Extract encrypted messages from JSON packets
     * The JSON string to be extracted for @ param json context
     * @return Extract encrypted message string
     */
    public static Object[] extract(String jsontext) {
        Object[] result = new Object[3];
        try {

            JSONObject json = new JSONObject(jsontext);
            String encrypt_msg = json.getString("encrypt");
            String tousername = json.getString("tousername");
            String agentid = json.getString("agentid");

            result[0] = tousername;
            result[1] = encrypt_msg;
            result[2] = agentid;
            return result;
        } catch (Exception e) {
            throw ThirdPartyApiException.asRDP().with(e, WechatI18nKey2.WECHAT_PARSE_JSON_ERROR);
        }
    }

    /**
     * Generate JSON message
     * @param encrypt encrypted message ciphertext
     * @param signature secure signature
     * @paramtimestamp timestamp
     * @param nonce random string
     * JSON string generated by @ return
     */
    public static String generate(String encrypt, String signature, String timestamp, String nonce) {

        String format = "{\"encrypt\":\"%1$s\",\"msgsignature\":\"%2$s\",\"timestamp\":\"%3$s\",\"nonce\":\"%4$s\"}";
        return String.format(format, encrypt, signature, timestamp, nonce);

    }
}
