import dayjs from '@/utils/dayjsSetup';
import i18n from '@/i18n';
import DataSourceGroup from '../views/dataSourceGroup.json';

export const formatTime = (value, fmt = 'YYYY/MM/DD') => dayjs(value).format(fmt);

export const toUtcISOString = (value) => {
  const time = dayjs(value);
  return time.isValid() ? time.toISOString() : '';
};

export const generateData = (list) => list;

export const noStruct = (type) => ['Redis', 'Valkey'].includes(type);

export const isPG = (type) => DataSourceGroup.pg.includes(type);
export const isMySQL = (type) => DataSourceGroup.mysql.includes(type);
export const isOracle = (type) => DataSourceGroup.oracle.includes(type);
export const isMongoDB = (type) => DataSourceGroup.mongo.includes(type);
export const isCk = (type) => DataSourceGroup.ck.includes(type);
export const separatePort = (type) =>
  ![
    'Kudu',
    'Redis',
    'ElastiCache',
    'ClickHouse',
    'ElasticSearch',
    'RabbitMQ',
    'RocketMQ',
    'Kafka',
    'MongoDB',
    'DocumentDB',
    'PolarDbX',
    'MaxCompute',
    'StarRocks',
    'Doris',
    'SelectDB',
    'Iceberg',
    'Pulsar',
    'OssFile',
    'S3File',
    'RagApi',
    'OpenAI',
    'DashScope',
    'HuggingFace',
    'Cohere',
    'DeepSeek',
    'LocalAI',
    'Ollama',
    'ZhipuAI',
    'Anthropic',
    'Bedrock',
    'DuckDB',
    'GoogleDrive',
    'Paimon',
    'Yuque',
    'DynamoDB',
    'DataLakeFormation',
    'AmazonMSK'
  ].includes(type);

export const showActiveLicense = (status) => [550, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566].includes(status);

export const NODE_TYPE = {
  ENV: 'ENV',
  INSTANCE: 'INSTANCE',
  CATALOG: 'CATALOG',
  SCHEMA: 'SCHEMA'
};

export const DS_RIGHT_CLICK_MENU_ITEM = {
  MENU_BROWSE_CONSOLE: 'MENU_BROWSE_CONSOLE',
  MENU_BROWSE_COPY_NAME: 'MENU_BROWSE_COPY_NAME',
  MENU_BROWSE_COPY_JDBC: 'MENU_BROWSE_COPY_JDBC',
  MENU_BROWSE_PERMISSIONS: 'MENU_BROWSE_PERMISSIONS',
  // ***** Copy / /
  MENU_BROWSE_REFRESH: 'MENU_BROWSE_REFRESH',
  MENU_BROWSE_INSTANCE_REFRESH: 'MENU_BROWSE_INSTANCE_REFRESH',
  MENU_BROWSE_CATALOG_REFRESH: 'MENU_BROWSE_CATALOG_REFRESH',
  MENU_BROWSE_SCHEMA_REFRESH: 'MENU_BROWSE_SCHEMA_REFRESH',
  // ***** //
  MENU_BROWSE_INSTANCE_CREATE: 'MENU_BROWSE_INSTANCE_CREATE',
  MENU_BROWSE_INSTANCE_RENAME: 'MENU_BROWSE_INSTANCE_RENAME',
  MENU_BROWSE_INSTANCE_DROP: 'MENU_BROWSE_INSTANCE_DROP',
  // ***** //
  MENU_BROWSE_CATALOG_CREATE: 'MENU_BROWSE_CATALOG_CREATE',
  MENU_BROWSE_CATALOG_RENAME: 'MENU_BROWSE_CATALOG_RENAME',
  MENU_BROWSE_CATALOG_DROP: 'MENU_BROWSE_CATALOG_DROP',
  // ***** //
  MENU_BROWSE_SCHEMA_CREATE: 'MENU_BROWSE_SCHEMA_CREATE',
  MENU_BROWSE_SCHEMA_DROP: 'MENU_BROWSE_SCHEMA_DROP',
  MENU_BROWSE_SCHEMA_RENAME: 'MENU_BROWSE_SCHEMA_RENAME',
  // ***** //
  MENU_BROWSE_TABLE_CREATE: 'MENU_BROWSE_TABLE_CREATE'
};

export const TABLE_RIGHT_CLICK_MENU_ITEM = {
  MENU_BROWSE_COPY_NAME: 'MENU_BROWSE_COPY_NAME',
  MENU_BROWSE_PERMISSIONS: 'MENU_BROWSE_PERMISSIONS',
  MENU_BROWSE_PROPERTY: 'MENU_BROWSE_PROPERTY',
  // ***** //
  MENU_BROWSE_REFRESH: 'MENU_BROWSE_REFRESH',
  MENU_BROWSE_KEY_REFRESH: 'MENU_BROWSE_KEY_REFRESH',
  MENU_BROWSE_KEY_RENAME: 'MENU_BROWSE_KEY_RENAME',
  MENU_BROWSE_KEY_DROP: 'MENU_BROWSE_KEY_DROP',
  MENU_BROWSE_VIEW_REFRESH: 'MENU_BROWSE_VIEW_REFRESH',
  MENU_BROWSE_TABLE_REFRESH: 'MENU_BROWSE_TABLE_REFRESH',
  MENU_BROWSE_COLUMN_REFRESH: 'MENU_BROWSE_COLUMN_REFRESH',
  MENU_BROWSE_INDEX_REFRESH: 'MENU_BROWSE_INDEX_REFRESH',
  MENU_BROWSE_PARTITION_REFRESH: 'MENU_BROWSE_PARTITION_REFRESH',
  MENU_BROWSE_PRIMARY_REFRESH: 'MENU_BROWSE_PRIMARY_REFRESH',
  MENU_BROWSE_REFRESH_DICT: 'MENU_BROWSE_REFRESH_DICT',
  // TABLE
  MENU_BROWSE_TABLE_CREATE: 'MENU_BROWSE_TABLE_CREATE',
  MENU_BROWSE_TABLE_RENAME: 'MENU_BROWSE_TABLE_RENAME',
  MENU_BROWSE_TABLE_ALTER: 'MENU_BROWSE_TABLE_ALTER',
  MENU_BROWSE_TABLE_DATA: 'MENU_BROWSE_TABLE_DATA',
  MENU_BROWSE_TABLE_TRUNCATE: 'MENU_BROWSE_TABLE_TRUNCATE',
  MENU_BROWSE_TABLE_DROP: 'MENU_BROWSE_TABLE_DROP',
  MENU_BROWSE_TABLE_IMPORT: 'MENU_BROWSE_TABLE_IMPORT',
  MENU_BROWSE_TABLE_EXPORT: 'MENU_BROWSE_TABLE_EXPORT',
  MENU_BROWSE_TABLE_REQUEST: 'MENU_BROWSE_TABLE_REQUEST',
  MENU_BROWSE_TABLE_GENERATE: 'MENU_BROWSE_TABLE_GENERATE',
  MENU_BROWSE_TABLE_GET_DDL: 'MENU_BROWSE_TABLE_GET_DDL',
  MENU_BROWSE_TABLE_FAKER: 'MENU_BROWSE_TABLE_FAKER',
  MENU_BROWSE_TABLE_FAKER_INCREMENT: 'MENU_BROWSE_TABLE_FAKER_INCREMENT',
  MENU_BROWSE_INDEX_DROP: 'MENU_BROWSE_INDEX_DROP',
  MENU_BROWSE_PRIMARY_DROP: 'MENU_BROWSE_PRIMARY_DROP',
  // VIEW
  MENU_BROWSE_VIEW_CREATE: 'MENU_BROWSE_VIEW_CREATE',
  MENU_BROWSE_VIEW_ALTER: 'MENU_BROWSE_VIEW_ALTER',
  MENU_BROWSE_VIEW_DATA: 'MENU_BROWSE_VIEW_DATA',
  MENU_BROWSE_VIEW_RENAME: 'MENU_BROWSE_VIEW_RENAME',
  MENU_BROWSE_VIEW_DROP: 'MENU_BROWSE_VIEW_DROP',
  MENU_BROWSE_VIEW_REQUEST: 'MENU_BROWSE_VIEW_REQUEST',
  MENU_BROWSE_VIEW_COMPILE: 'MENU_BROWSE_VIEW_COMPILE',
  // MATERIALIZED
  MENU_BROWSE_MATERIALIZED_REQUEST: 'MENU_BROWSE_MATERIALIZED_REQUEST',
  MENU_BROWSE_MATERIALIZED_DROP: 'MENU_BROWSE_MATERIALIZED_DROP',
  // SYNONYM
  MENU_BROWSE_SYNONYM_REQUEST: 'MENU_BROWSE_SYNONYM_REQUEST',
  // TRIGGER
  MENU_BROWSE_TRIGGER_CREATE: 'MENU_BROWSE_TRIGGER_CREATE',
  MENU_BROWSE_TRIGGER_DROP: 'MENU_BROWSE_TRIGGER_DROP',
  MENU_BROWSE_TRIGGER_ALTER: 'MENU_BROWSE_TRIGGER_ALTER',
  MENU_BROWSE_TRIGGER_COMPILE: 'MENU_BROWSE_TRIGGER_COMPILE',
  MENU_BROWSE_TRIGGER_REQUEST: 'MENU_BROWSE_TRIGGER_REQUEST',
  // FUNCTION
  MENU_BROWSE_FUNCTION_CREATE: 'MENU_BROWSE_FUNCTION_CREATE',
  MENU_BROWSE_FUNCTION_ALTER: 'MENU_BROWSE_FUNCTION_ALTER',
  MENU_BROWSE_FUNCTION_DROP: 'MENU_BROWSE_FUNCTION_DROP',
  MENU_BROWSE_FUNCTION_COMPILE: 'MENU_BROWSE_FUNCTION_COMPILE',
  MENU_BROWSE_FUNCTION_REQUEST: 'MENU_BROWSE_FUNCTION_REQUEST',
  // PROCEDURE
  MENU_BROWSE_PROCEDURE_CREATE: 'MENU_BROWSE_PROCEDURE_CREATE',
  MENU_BROWSE_PROCEDURE_ALTER: 'MENU_BROWSE_PROCEDURE_ALTER',
  MENU_BROWSE_PROCEDURE_DROP: 'MENU_BROWSE_PROCEDURE_DROP',
  MENU_BROWSE_PROCEDURE_COMPILE: 'MENU_BROWSE_PROCEDURE_COMPILE',
  MENU_BROWSE_PROCEDURE_REQUEST: 'MENU_BROWSE_PROCEDURE_REQUEST',
  // DBLINK
  MENU_BROWSE_DBLINK_CREATE: 'MENU_BROWSE_DBLINK_CREATE',
  MENU_BROWSE_DBLINK_DROP: 'MENU_BROWSE_DBLINK_DROP',
  MENU_BROWSE_DBLINK_TEST: 'MENU_BROWSE_DBLINK_TEST',
  // JOB
  MENU_BROWSE_JOB_CREATE: 'MENU_BROWSE_JOB_CREATE',
  MENU_BROWSE_JOB_ALTER: 'MENU_BROWSE_JOB_ALTER',
  MENU_BROWSE_JOB_DROP: 'MENU_BROWSE_JOB_DROP',
  MENU_BROWSE_JOB_DISABLE: 'MENU_BROWSE_JOB_DISABLE',
  MENU_BROWSE_JOB_ENABLE: 'MENU_BROWSE_JOB_ENABLE',
  MENU_BROWSE_JOB_RUN: 'MENU_BROWSE_JOB_RUN',
  // SCHEDULE JOB
  MENU_BROWSE_SCHEDULE_DROP: 'MENU_BROWSE_SCHEDULE_DROP',
  MENU_BROWSE_SCHEDULE_ENABLE: 'MENU_BROWSE_SCHEDULE_ENABLE',
  MENU_BROWSE_SCHEDULE_DISABLE: 'MENU_BROWSE_SCHEDULE_DISABLE',
  MENU_BROWSE_SCHEDULE_RUN: 'MENU_BROWSE_SCHEDULE_RUN',
  MENU_BROWSE_SCHEDULE_CREATE: 'MENU_BROWSE_SCHEDULE_CREATE',
  // CONSTRAINT
  MENU_BROWSE_CONSTRAINT_ENABLE: 'MENU_BROWSE_CONSTRAINT_ENABLE',
  MENU_BROWSE_CONSTRAINT_DISABLE: 'MENU_BROWSE_CONSTRAINT_DISABLE',
  // USER
  MENU_BROWSE_USER_DROP: 'MENU_BROWSE_USER_DROP'
};

export const SOCKET_TYPE = {
  WS_ASYNC_EVENT: 'WS_ASYNC_EVENT'
};

export const ASYNC_TASK_STATUS = {
  INIT: 'INIT',
  BLOCK: 'BLOCK',
  WAIT_START: 'WAIT_START',
  RUNNING: 'RUNNING',
  FAILURE: 'FAILURE',
  CANCEL: 'CANCEL',
  COMPLETE: 'COMPLETE',
  PAUSE: 'PAUSE'
};

export const FAKER_TASK_STATUS = {
  INIT: 'INIT',
  RUNNING: 'RUNNING',
  PAUSE: 'PAUSE',
  COMPLETE: 'COMPLETE',
  WAITING_RESUME: 'WAITING_RESUME',
  WAITING_PAUSE: 'WAITING_PAUSE'
};

export const WS_TYPE = {
  WS_REQ_QUERY: 'WS_REQ_QUERY',
  WS_REQ_ECHO: 'WS_REQ_ECHO',
  WS_RES_QUERY: 'WS_RES_QUERY',
  WS_RES_ECHO: 'WS_RES_ECHO',
  WS_REQ_LANGUAGE: 'WS_REQ_LANGUAGE',
  WS_RES_LANGUAGE: 'WS_RES_LANGUAGE',
  WS_RES_ERROR: 'WS_RES_ERROR',
  WS_RES_ASYNC_EVENT: 'WS_RES_ASYNC_EVENT',
  WS_RES_DRIVER_DOWNLOAD_EVENT: 'WS_RES_DRIVER_DOWNLOAD_EVENT',
  WS_SYS_STATUS: 'WS_SYS_STATUS',
  WS_RES_EXPORT_EVENT: 'WS_RES_EXPORT_EVENT'
};

export const WS_REQ_QUERY_TYPE = {
  REQUEST_QUERY: 'RequestQuery',
  REQUEST_PLAN: 'RequestPlan',
  CANCEL_QUERY: 'CancelQuery',
  SWITCH_CTX: 'SwitchCtx',
  TX_STATUS: 'TxStatus',
  TX_COMMIT: 'TxCommit',
  TX_ROLLBACK: 'TxRollback',
  RECOVER_STATUS: 'RecoveryStatus',
  EXPLAIN: 'ExplainQuery'
};

export const RULE_WARN_LEVEL = {
  SUGGEST: i18n.global.t('ti-shi'),
  FAILURE: i18n.global.t('zu-sai')
};
